#!/bin/bash
# init.sh - Initial import of existing Cloudflare IP access rules
# This script should be run ONCE to import existing rules into Terraform management

set -e

echo "🚀 Cloudflare IP Access Rules - Initial Import"
echo "=============================================="
echo ""

# Check if terraform.tfvars exists
if [ ! -f "terraform.tfvars" ]; then
  echo "❌ Error: terraform.tfvars not found"
  echo ""
  echo "Please create terraform.tfvars from the example:"
  echo "  cp terraform.tfvars.example terraform.tfvars"
  echo "  # Edit terraform.tfvars and add your API token"
  exit 1
fi

# Extract values from terraform.tfvars
API_TOKEN=$(grep 'cloudflare_api_token' terraform.tfvars | cut -d'"' -f2)
ACCOUNT_ID=$(grep 'cloudflare_account_id' terraform.tfvars | cut -d'"' -f2)
ZONE_ID=$(grep 'cloudflare_zone_id' terraform.tfvars | cut -d'"' -f2)

if [ -z "$API_TOKEN" ] || [ "$API_TOKEN" = "token here" ]; then
  echo "❌ Error: API token not configured in terraform.tfvars"
  echo ""
  echo "Please edit terraform.tfvars and set your Cloudflare API token"
  exit 1
fi

echo "📋 Configuration:"
echo "  Account ID: $ACCOUNT_ID"
echo "  Zone ID: $ZONE_ID"
echo ""

# Check if jq is installed
if ! command -v jq &> /dev/null; then
  echo "❌ Error: jq is not installed"
  echo ""
  echo "Please install jq:"
  echo "  Ubuntu/Debian: sudo apt-get install jq"
  echo "  MacOS: brew install jq"
  exit 1
fi

# Fetch existing rules
echo "🔍 Step 1: Fetching existing rules from Cloudflare..."
echo ""

echo "  Fetching account-level rules..."
curl -s -X GET "https://api.cloudflare.com/client/v4/accounts/${ACCOUNT_ID}/firewall/access_rules/rules" \
  -H "Authorization: Bearer ${API_TOKEN}" \
  -H "Content-Type: application/json" > /tmp/account-rules.json

ACCOUNT_COUNT=$(jq '.result | length' /tmp/account-rules.json 2>/dev/null || echo "0")
echo "  Found: $ACCOUNT_COUNT account-level rules"

echo "  Fetching zone-level rules..."
curl -s -X GET "https://api.cloudflare.com/client/v4/zones/${ZONE_ID}/firewall/access_rules/rules" \
  -H "Authorization: Bearer ${API_TOKEN}" \
  -H "Content-Type: application/json" > /tmp/zone-rules.json

ZONE_COUNT=$(jq '.result | length' /tmp/zone-rules.json 2>/dev/null || echo "0")
echo "  Found: $ZONE_COUNT zone-level rules"

TOTAL_COUNT=$((ACCOUNT_COUNT + ZONE_COUNT))

if [ "$TOTAL_COUNT" -eq 0 ]; then
  echo ""
  echo "✅ No existing rules found in Cloudflare"
  echo ""
  echo "You can now add rules to shared/config.yaml and run:"
  echo "  terraform init"
  echo "  terraform plan"
  echo "  terraform apply"
  exit 0
fi

echo ""
echo "📝 Step 2: Generating shared/config.yaml..."
echo ""

# Backup existing config.yaml if it exists
if [ -f "shared/config.yaml" ]; then
  BACKUP_FILE="shared/config.yaml.backup.$(date +%Y%m%d_%H%M%S)"
  cp "shared/config.yaml" "$BACKUP_FILE"
  echo "  Backup created: $BACKUP_FILE"
fi

# Generate config.yaml header
cat > shared/config.yaml << 'EOF'
# Cloudflare IP Access Rules Configuration
# Auto-generated by init.sh on $(date)
# 
# Fields:
#   ip (required): IP address or CIDR range
#   mode (required): block, challenge, whitelist, js_challenge, managed_challenge
#   scope (optional): "account" or "zone" - defaults to "account"
#   notes (required): Explanation with date/reason

ip_access_rules:
EOF

# Add account-level rules
if [ "$ACCOUNT_COUNT" -gt 0 ]; then
  echo "  # Account-level rules" >> shared/config.yaml
  jq -r '.result[] | "  - ip: \"\(.configuration.value)\"\n    mode: \"\(.mode)\"\n    scope: \"account\"\n    notes: \"\(.notes // "Imported from Cloudflare on " + (now | strftime("%Y-%m-%d")))\"" ' /tmp/account-rules.json >> shared/config.yaml
  echo "  Added $ACCOUNT_COUNT account-level rules"
fi

# Add zone-level rules
if [ "$ZONE_COUNT" -gt 0 ]; then
  echo "" >> shared/config.yaml
  echo "  # Zone-level rules" >> shared/config.yaml
  jq -r '.result[] | "  - ip: \"\(.configuration.value)\"\n    mode: \"\(.mode)\"\n    scope: \"zone\"\n    notes: \"\(.notes // "Imported from Cloudflare on " + (now | strftime("%Y-%m-%d")))\"" ' /tmp/zone-rules.json >> shared/config.yaml
  echo "  Added $ZONE_COUNT zone-level rules"
fi

echo ""
echo "✅ Config generated: shared/config.yaml"
echo ""

# Initialize Terraform
echo "🔧 Step 3: Initializing Terraform..."
echo ""
terraform init

echo ""
echo "📥 Step 4: Importing rules into Terraform state..."
echo ""

IMPORTED=0
FAILED=0

# Import account-level rules
if [ "$ACCOUNT_COUNT" -gt 0 ]; then
  echo "  Importing account-level rules..."
  jq -r '.result[] | "\(.id) \(.configuration.value)"' /tmp/account-rules.json | while read -r rule_id ip; do
    key="account-${ip//\//-}"
    echo "    Importing: $key"
    
    if terraform import "module.security.cloudflare_access_rule.ip_rules[\"${key}\"]" "accounts/${ACCOUNT_ID}/${rule_id}" 2>&1 | grep -q "Import successful"; then
      echo "      ✅ Success"
      IMPORTED=$((IMPORTED + 1))
    else
      echo "      ⚠️  Failed or already imported"
      FAILED=$((FAILED + 1))
    fi
  done
fi

# Import zone-level rules
if [ "$ZONE_COUNT" -gt 0 ]; then
  echo "  Importing zone-level rules..."
  jq -r '.result[] | "\(.id) \(.configuration.value)"' /tmp/zone-rules.json | while read -r rule_id ip; do
    key="zone-${ip//\//-}"
    echo "    Importing: $key"
    
    if terraform import "module.security.cloudflare_access_rule.ip_rules[\"${key}\"]" "zones/${ZONE_ID}/${rule_id}" 2>&1 | grep -q "Import successful"; then
      echo "      ✅ Success"
      IMPORTED=$((IMPORTED + 1))
    else
      echo "      ⚠️  Failed or already imported"
      FAILED=$((FAILED + 1))
    fi
  done
fi

echo ""
echo "✅ Step 5: Verifying import..."
echo ""
terraform plan

echo ""
echo "=============================================="
echo "🎉 Initial import complete!"
echo "=============================================="
echo ""
echo "Summary:"
echo "  Total rules found: $TOTAL_COUNT"
echo "  Config generated: shared/config.yaml"
echo "  Terraform initialized: ✅"
echo ""
echo "Next steps:"
echo "  1. Review shared/config.yaml"
echo "  2. Run 'terraform plan' to verify (should show no changes)"
echo "  3. Add new rules to shared/config.yaml as needed"
echo "  4. Run 'terraform apply' to push changes"
echo ""
echo "⚠️  IMPORTANT: From now on, all IP access rules must be managed via Terraform."
echo "   Do not make manual changes in the Cloudflare dashboard."
echo ""
